// WARNING: DO NOT DELETE THIS FILE
// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten except
// each contracts' constructor arguments (you can freely edit those and the compiler will respect them).

const WitnetParserLib = artifacts.require("WitnetParserLib")
const WitnetProxy = artifacts.require("WitnetProxy")
const PriceFeed = artifacts.require("PriceFeed")

module.exports = async function (deployer) {
  await deployer.link(WitnetParserLib, [PriceFeed])
  await deployer.deploy(PriceFeed, WitnetProxy.address)
  const priceFeed = await PriceFeed.deployed()
  await priceFeed.initialize()
}
